spring:
  application:
    name: hello-client

server:
  port: 8072

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8070/eureka
  instance:
    hostname: localhost

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000